CREATE DATABASE DEPART;
USE DEPART;
CREATE TABLE dept(
DEPTNo int NOT NULL,
DNAME varchar(30) NOT NULL,
LOC varchar(30) NOT NULL);
SELECT * FROM dept;
RENAME TABLE dept TO department;
Alter TABLE department ADD COLUMN PINCODE int(7) NOT NULL;
ALTER TABLE department  DROP COLUMN PINCODE;
ALTER TABLE department CHANGE DNAME DEPT_NAME VARCHAR(20);
ALTER TABLE department MODIFY COLUMN LOC CHAR(10);
SELECT * FROM department;
DROP TABLE department;